version: 1.0.0

database:
  image: "postgres:15.1-alpine"
  driver: "postgres"
  user: "bookstore"
  password: "_b00kSt0r3_"
  host: "localhost"
  port: "5431"
  schema: "bookstore-author"

http-server:
  port: "1323"
